# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQ6b1fBbTI6sHUFlqDM0k4qliyFiLUBP
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(page_title="FAA Wildlife Strike Explorer", layout="wide")

# 1. 数据加载与缓存
@st.cache_data
def load_data():
    try:
        df = pd.read_csv('wildlife_strikes.csv'，encoding='latin-1')
        df['INCIDENT_DATE'] = pd.to_datetime(df['INCIDENT_DATE'])
        df['YEAR'] = df['INCIDENT_DATE'].dt.year
        return df
    except FileNotFoundError:
        st.error("请确保数据文件 'wildlife_strikes.csv' 已上传至 GitHub 仓库。")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    # --- 侧边栏交互 (Dynamic Queries) ---
    st.sidebar.header("数据探索过滤器")

    # 年份选择滑块
    year_range = st.sidebar.slider(
        "选择年份范围",
        int(df['YEAR'].min()), int(df['YEAR'].max()),
        (int(df['YEAR'].min()), int(df['YEAR'].max()))
    )

    # 飞行阶段多选
    phases = st.sidebar.multiselect(
        "选择飞行阶段",
        options=df['PHASE_OF_FLIGHT'].unique(),
        default=df['PHASE_OF_FLIGHT'].unique()
    )

    # 数据过滤逻辑
    filtered_df = df[
        (df['YEAR'] >= year_range[0]) &
        (df['YEAR'] <= year_range[1]) &
        (df['PHASE_OF_FLIGHT'].isin(phases))
    ]

    # --- 主界面展示 ---
    st.title("✈️ FAA 野生动物撞击交互式分析仪表板")
    st.markdown("本应用旨在探索美国航空安全中的鸟击事件及其造成的经济损失。")

    # 关键指标卡片
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("总撞击事件", f"{len(filtered_df):,}")
    with col2:
        total_cost = filtered_df['COST_REPAIRS'].sum()
        st.metric("维修总成本", f"${total_cost:,.0f}")
    with col3:
        damage_rate = (filtered_df['DAMAGE'].notnull().sum() / len(filtered_df)) * 100
        st.metric("导致损坏比例", f"{damage_rate:.1f}%")

    # 图表 1: 时间趋势 (支持 Zooming/Panning)
    st.subheader("📊 历年撞击趋势分析")
    trend_data = filtered_df.groupby('YEAR').size().reset_index(name='Count')
    fig_line = px.line(trend_data, x='YEAR', y='Count',
                      title="选定范围内的年度事件频率",
                      labels={'Count': '撞击次数', 'YEAR': '年份'},
                      template="plotly_white")
    st.plotly_chart(fig_line, use_container_width=True)

    # 图表 2: 鸟类品种与成本 (Details-on-demand via Tooltips)
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("🦜 涉及的主要鸟类品种")
        species_data = filtered_df['SPECIES'].value_counts().head(10).reset_index()
        fig_bar = px.bar(species_data, x='count', y='SPECIES', orientation='h',
                        title="前十大撞击物种",
                        color='count',
                        labels={'count': '发生次数', 'SPECIES': '物种'},
                        hover_data={'count': True})
        st.plotly_chart(fig_bar, use_container_width=True)

    with col_right:
        st.subheader("💰 维修成本与飞行高度关系")
        fig_scatter = px.scatter(filtered_df, x='HEIGHT', y='COST_REPAIRS',
                                color='PHASE_OF_FLIGHT',
                                size='COST_REPAIRS',
                                title="高度 vs 成本 (气泡大小代表金额)",
                                hover_name='AIRPORT',
                                labels={'HEIGHT': '高度 (英尺)', 'COST_REPAIRS': '维修成本 ($)'})
        st.plotly_chart(fig_scatter, use_container_width=True)

else:
    st.warning("等待加载数据...")

